# -*- coding: utf-8 -*-
"""Copy of Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1663eiuZrZXMX1c99rqYvzqGElst1d6Ic
"""

import streamlit as st
import wolframalpha

# Set up the Wolfram Alpha API client
app_id = '7W8XJW-PTWKYLQJ2K'
client = wolframalpha.Client(app_id)

# Streamlit app header
st.title("ChatGPT with Wolfram Alpha")

# User input section
user_input = st.text_input("Ask a question")

# Check if user input is provided
if user_input:
    # Query Wolfram Alpha API
    res = client.query(user_input)
    
    # Check if Wolfram Alpha has a response
    if res['@success'] == 'true':
        # Parse the response and extract the answer
        answer = next(res.results).text
        st.success(answer)
    else:
        st.warning("Sorry, I couldn't find an answer to your question.")